### ISSUE TITLE
font size bug on iOS

### ISSUE THREAD

**Issue by landvibe** [readium/readium-js#100]
safari and chrome show same bug

what I found is...
- when I go to next spine (by pressing next button), the font size is changed to any big size.
- when i change the screen mode(portrait <-> landscape), the right font size comes back
- non-working devices: iphone5s(8.3), iphone4s(7.0.4)
- working devices: iphone6(8.3), iPad-mini(8.2)

this is my test epub file
https://www.dropbox.com/s/livmyrv8nsmv6ic/bookcube_sample.epub?dl=0

**Comment by landvibe** [comment]
this image shows the correct font size.
![img_0608](https://cloud.githubusercontent.com/assets/3401416/7529088/0aa0f4ac-f56e-11e4-86d5-82828c678c16.PNG)

this image shows the bug font size.
![img_0610](https://cloud.githubusercontent.com/assets/3401416/7529090/1053986e-f56e-11e4-927a-e7ad32d614ff.PNG)

font-size, height and line-height is different between them.

**Comment by danielweck** [comment]
`ReadiumSDK.Helpers.UpdateHtmlFontSize()` updates CSS `line-height` as well as `font-size`:
https://github.com/readium/readium-shared-js/blob/develop/js/helpers.js#L99

This function should be invoked during page refresh, e.g. when the aspect ratio or the dimensions of viewport changes. Would you be able to trace this function call, and check what font size is passed as argument? (it should match the global Readium preferences)

**Comment by landvibe** [comment]
It matches the global Readium preferences.
fontSize of UpdateHtmlFontSize = fontSize of settings = 100

**Comment by landvibe** [comment]
I think it is a race condition.

I repeated below sequence many times.
clear safari cache -> open the web page
and I meet the bug sometimes (not everytime)

below value is different between the bug and non-bug.
in updatePagination function -> style.fontSize

**Comment by danielweck** [comment]
Interesting. Thanks for your feedback @landvibe !
@JCCR do you think that this is related to your observed font-size discrepancies when instantiating several reader views?

**Comment by landvibe** [comment]
It is dependent on epub file.
Some epub files do not show this bug.

**Comment by danielweck** [comment]
I am not able to reproduce this with the latest changes in `UpdateHtmlFontSize` (custom font loader / resize sensor)
