### ISSUE TITLE
HTML spine item inner iframes (e.g. widgets) lack MathJax and navigator.epubReadingSystem

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js#107]
Follow-up to: https://github.com/readium/readium-js-viewer/issues/356

Spine item documents are correctly pre-processed ( https://github.com/readium/readium-js/blob/develop/epub-modules/Readium.js#L39 ) in order to:
(1) inject the navigator.epubReadingSystem object
(2) inject the MathJax "bootstrapper"
(3) plug / block / redirect the window.top/parent properties
This process relies on a "shallow" content parser (HTML DOM only), just to load the spine item HTML markup in the top-level iframe, via BlobURi. Consequently, inner iframes are *not* pre-processed, resulting in EPUB "widgets" lacking support for MathML and the epubReadingSystem object.

Note that loading zipped-EPUB (and expanded EPUBs that contain obfuscated fonts) relies on a "deep" content parser (HTML DOM, CSS, etc.) so that *all resources* are loaded via BlobURis, including inner iframes (this process was coined "programmatic fetching"). Unfortunately, in that particular scenario web browsers fail to instantiate "nested" BlobURi instances, and inner iframes fail to load. See https://github.com/readium/readium-js/issues/105#issue-78610044
I suspect that the same implementation caveat might exist for the generic cloud reader...to be verified.

**Comment by danielweck** [comment]
Related issue (nested iframe loaders): https://github.com/readium/readium-js/issues/105

**Comment by rkwright** [comment]
This is a critical bug as it means that widgets will not be fully operational (no MathML, etc.).  this clearly is a problem for EDUPUB workflows.

**Comment by danielweck** [comment]
Fixed in plugins feature branch:
https://github.com/readium/readium-js/commit/7d3efed59288a0823f12195d565d117ffb37ae9c

Demonstration EPUB:
https://github.com/readium/readium-js-viewer/tree/feature/pluginsX/epub_content/epubReadingSystem

**Comment by danielweck** [comment]
Note: tested in Firefox and Chrome. Internet Explorer does not use BlobURI (instead: document.write()/close() API) and currently fails to load nested iframes.

**Comment by danielweck** [comment]
Follow-up to above comment: now works with IE too (nested iframes in both exploded and zipped EPUBs).
See: https://github.com/readium/readium-js/commit/e73bc0cf2f865a9d3c3b8f3c85ebfdfeff9a796d and https://github.com/readium/readium-js-viewer/commit/bde96d9b173c00191408064ec5a9c2d15f1a2d6f
