### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by outsideMyBox** [readium/readium-js#108]
Hi,

in the chapter "Development and contributing" README.md the links from the points
- How to contribute
- How to get set up for development.
- Some info about the file and folder structure of this project

don't point to any documentation.
Is there a documentation somewhere I could use to set everything up and understand the structure of  readium-js  ? 

Regards,
Franck

**Comment by danielweck** [comment]
The README has recently been updated (added "API" section): https://github.com/readium/readium-js/blob/develop/README.md#api
The "Development and contributing" section is indeed woefully out of date, including dead links.

Note that there is an ongoing feature branch where the build process and file organisation has been improved. This branch will be merged to develop within the next week or so. There will be a new API for plugins, and a refactored RequireJS / AMD architecture (across all ReadiumJS repositories).
https://github.com/readium/readium-js/blob/feature/pluginsX/README.md#readium-js
An example HTML file demonstrates how to bootstrap a reader instance with minimal UI:
https://github.com/readium/readium-js/blob/feature/pluginsX/dev/index.js

**Comment by outsideMyBox** [comment]
Hi Daniel,
thanks for the clarification and the links. Can't wait to test the new develop version!
