### ISSUE TITLE
Question: iframe_zip_loader in Windows 10 Edge

### ISSUE THREAD

**Issue by chine** [readium/readium-js#112]
We've noticed that this line:
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/iframe_zip_loader.js#L18
is resulting Edge to be treated as not-IE (The Edge user agent naturally has no mention of Trident.). This prevents epubs from loading successfully. If we switch it to give the IE treatment to Edge, the epub will load.

Although we're currently on readium-js 0.18, I don't see any difference in the file that would alter this behavior.

I don't see any mention of Edge in the existing issues, are we perhaps the first to notice this?

**Comment by rkwright** [comment]
Our Windows support is relatively rudimentary so I suspect the answer is yes, you are the first ones to encounter this bug.  We would welcome your contribution in resolving this issue.

**Comment by chine** [comment]
Will do. We need to resolve the issue for ourselves in out fork sooner than we'll be updating to 0.2x anyway.

**Comment by rkwright** [comment]
OK, please let the group know if you need help.

**Comment by danielweck** [comment]
Closed via PR https://github.com/readium/readium-js/pull/113
(I am now using Windows 10 and I have started testing Edge)
