### ISSUE TITLE
Regression bug since CryptoJS is external library dependency: obfuscated fonts SHA1 (byte array)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js#125]

**Comment by danielweck** [comment]
Fixed here: https://github.com/readium/readium-js/commit/51948fffd7288c69c3ad762e239b765c53f8aad5#diff-725fd66068801adf5d7c9df7d42d3842L109

**Comment by rkwright** [comment]
Re-opening until fix is verified in release 0.22.1
