### ISSUE TITLE
init Readium

### ISSUE THREAD

**Issue by benson-jala** [readium/readium-js#127]
i added readium-js_all.js to my build.
now how to initialize readium object to my web app.

**Comment by danielweck** [comment]
This is the RequireJS single-bundle of AMD modules. You can get inspiration from this example:
https://github.com/readium/readium-js/blob/develop/dev/index_RequireJS_single-bundle.html

...although I would recommend checking how it's done in a "real", such as readium-js-viewer:
https://github.com/readium/readium-js-viewer/blob/develop/dev/index_RequireJS_single-bundle.html

The above application "bootstrappers" are for _development_ mode, using the exploded source code and application assets (images resources, CSS stylesheets, fonts, etc.). If instead you need to deploy a distributable package, you may take a look at:
https://github.com/readium/readium-js-viewer/blob/develop/src/cloud-reader/index.html

...and more importantly, read the build instructions in the README:
https://github.com/readium/readium-js-viewer/blob/develop/README.md

I hope this helps. Regards, Daniel
