### ISSUE TITLE
Hover dialogue doesn't disappear if certain actions are done.

### ISSUE THREAD

**Issue by dahnny012** [readium/readium-js#131]
If a user clicks on the table of contents and then presses tab the dialogue box for settings will remain superimposed on the application and there isn't a way to get rid of it. The user has to press tab and click at almost at the same time. The bug doesnt appear everytime
![screenshot 2016-01-08 at 6 45 37 am](https://cloud.githubusercontent.com/assets/3695724/12197323/f0bef30a-b5d3-11e5-8e96-277f46d34660.png)

 but with enough trials it the bug will appear.

 A user has to restart the app to get rid of it.

**Comment by danielweck** [comment]
Duplicate: https://github.com/readium/readium-js-viewer/issues/434
