### ISSUE TITLE
Regression bug in Chrome 49 (was okay in 48) MathJax font cache (SVG paths)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js#138]
Live tests:

https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2Fmichal-h21%2Fepub3sample%2Fmaster%2Fhsmmt10t.epub&goto=%7B%22idref%22%3A%22file12%22%2C%22elementCfi%22%3A%22%2F4%2F6%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D

https://readium.firebaseapp.com/?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Flinear-algebra&goto=%7B"idref"%3A"c56"%2C"elementCfi"%3A"%2F4%5Bd1e33%5D%2F4%2C%2F1%3A0%2C%2F1%3A1"%7D

https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2Fsarabander%2Fsicp-epub%2Fmaster%2Fexploded&goto=%7B%22idref%22%3A%22x1_002e2%22%2C%22elementCfi%22%3A%22%2F4%2F4%2F218%2F2%2C%2F17%3A1%2C%2F17%3A2%22%7D

See source code where the font cache is disabled for Firefox and Edge:
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/iframe_zip_loader.js#L209

Related: https://github.com/michal-h21/tex4ebook/issues/23#issuecomment-195417096
Related: https://github.com/sarabander/sicp/issues/12#issuecomment-196293761

CC @pkra

**Comment by pkra** [comment]
Thanks for moving this here.

**Comment by pkra** [comment]
If I trigger a MathJax re-render in the console (`MathJax.Hub.Queue(["Rerender",MathJax.Hub])`), I get lots of errors along the lines of

`MathJax.js:27 Unsafe attempt to load URL https://cdn.rawgit.com/michal-h21/epub3sample/master/hsmmt10t.epub/OEBPS/hsmmt10tch13.xhtml from frame with URL blob:https%3A//readium.firebaseapp.com/f1710ecf-9532-481b-bd19-d43971f8390c. Domains, protocols and ports must match.`

**Comment by pkra** [comment]
I'm guessing this means Chrome is blocking the use elements for security reasons. Maybe related to `base`? I have no clue :frowning:

**Comment by danielweck** [comment]
Fixed by disabling MathJax font / glyph cache (SVG paths + `use` element), just like Firefox and Edge (Internet Explorer still works fine): https://github.com/readium/readium-js/commit/e7f033b1aedefd5c631cf3c7d81074795333d5d5
Tested locally, will try again when app has finished deploying at Firebase (TravisCI in progress...)

**Comment by danielweck** [comment]
Fix / workaround succesfully tested with:

https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2Fmichal-h21%2Fepub3sample%2Fmaster%2Fhsmmt10t.epub&goto=%7B%22idref%22%3A%22file12%22%2C%22elementCfi%22%3A%22%2F4%2F6%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D

https://readium.firebaseapp.com/?epub=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Flinear-algebra&goto=%7B"idref"%3A"c56"%2C"elementCfi"%3A"%2F4%5Bd1e33%5D%2F4%2C%2F1%3A0%2C%2F1%3A1"%7D

https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2Fsarabander%2Fsicp-epub%2Fmaster%2Fexploded&goto=%7B%22idref%22%3A%22x1_002e2%22%2C%22elementCfi%22%3A%22%2F4%2F4%2F218%2F2%2C%2F17%3A1%2C%2F17%3A2%22%7D

**Comment by pkra** [comment]
Thanks for the update, @danielweck. Do I understand correctly that this is now a generic problem with `<base>`? Maybe we should make a universal fix upstream (or at least a note for devs).

**Comment by danielweck** [comment]
Yes, MathJax could detect `html>head>base@href` and enforce SVG `useFontCache=no` in web browsers / webviews that are known to fail with `<use xlink:href />`  in the HTML document.
