### ISSUE TITLE
Zoom Scaling

### ISSUE THREAD

**Issue by dilawer** [readium/readium-js#140]
Hello,

I am trying to play with zooming ability of readium (currently using it in iOS). I wan to do the following two things

- First: if user zoom in the page, I want to make it zoom out at a certain action and make it fit to viewable area. This is because when I zoom in and change the orientation of the screen, I want it to be fit to screen at that time
- Second: I want to increase the zoom level/scale of the page, can you suggest in which file and what part of code I need to change to make it work?

Thanks

@danielweck

**Comment by rkwright** [comment]
@dilawer I will let those with more in-depth knowledge respond, but be warned that this is a tricky area due to the convoluted algorithms used to render content on the page.  It's an area we would like to refactor going forward, but for now it is an area where adding a feature can easily cause a regression elsewhere.

**Comment by danielweck** [comment]
I suggest you take a look at how the cloud reader / Chrome extension expose a UI control (editable combo box / pull-down list) to allow users to enter a custom zoom level:
https://readium.firebaseapp.com/?epub=epub_content%2Fpage-blanche&goto=%7B%22idref%22%3A%22id-PageBlanche_Page_006-xhtml%22%2C%22elementCfi%22%3A%22%2F4%2F2%2F2%22%7D
Note that this only works with fixed-layout / FXL EPUB3 publications.
Try 100% to see how content panning can be performed manually within the scrolling viewport (which, as you can see, contains a 2-page spread).
The API is undocumented, but it basically comes down to `setZoom()` in fixed_view.js:
https://github.com/readium/readium-shared-js/blob/develop/js/views/fixed_view.js#L99
https://github.com/readium/readium-shared-js/blob/develop/js/views/fixed_view.js#L352
```javascript
        var scale;
        if (_zoom.style == 'fit-width'){
            scale = horScale;
        }
        else if (_zoom.style == 'fit-height'){
            scale = verScale;
        }
        else if (_zoom.style == 'user'){
            scale = _zoom.scale;
        }
        else{
            scale = Math.min(horScale, verScale);

            // no need for pan during "viewport fit" zoom
            _$viewport.css("overflow", "hidden");
        }

        _currentScale = scale;
```

So, the code to manipulate the basic zoom level is there already, based on an HTML layout method that uses CSS `overflow:scroll` across a single or two-page spread.
However, you will need to implement your own control logic to programmatically scroll / pan the content viewport into a desired area. 
Let us know how it goes, please!
Feel free to contribute a Pull Request if you feel that your implementation is worth sharing.
