### ISSUE TITLE
How to get TOC info after open a book?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#141]
I have successfully opened a book using readium-js.
I looked through readium object and readium.reader, but none of them contain data of TOC?

Where should I look at?
Thanks.

**Comment by JCCR** [comment]
Hi @hz0324 
You would think that it would be there but it's actually a part of the `packageDocument` object.
You get an instance of that as the first param value of the callback when you call `openPackageDocument`.

```
readium.openPackageDocument('someEbookUrl', function(packageDocument, options) {
    packageDocument.generateTocListDOM(function(tocDocument) {
        $(navDocDom).find('li > a').each(function() {
            console.log($(this).text(), $(this).attr('href'));
        });
    });
}, somePageRequest);
```

There are some edge cases to account for in the code snippet above. 
If you would prefer to get data back in a JSON format like this:
https://github.com/readium/readium-2/blob/develop/readium1-data-samples/accessible-epub-3%20/toc.json

Then I have some new code for that, but I need to make a pull request for it.

**Comment by hz0324** [comment]
Thank you for your excellent answer, it is really helpful.
I appreciate it a lot. ^_^

**Comment by hz0324** [comment]
By the way, is there a doc about this?

**Comment by JCCR** [comment]
We have this site:
http://readium.github.io/index.html

That has an API reference link on the side, but it looks to be outdated or has missing info.
http://readium.github.io/api/index.html

**Comment by hz0324** [comment]
Yep, they are not enough for deep usage
