### ISSUE TITLE
How to go to certain location using CFI?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#143]
I have read the API doc of ReaderView, but I didn't find a method that can go to certain location by CFI. 

We want to implement a note/highlight system, I guess we can get CFI of certain paragraph by calling getCurrentSelectionCfi(), but we don't know ho jump back to it using CFI. Please help, thanks.

**Comment by danielweck** [comment]
Take a look at how it's implemented in `readium-js-viewer`, for the `goto` URL query parameter, or for restoring the last saved reading location ("bookmark"):
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L1058
(search for `openPageRequest`, and see how it's passed to `readium.openPackageDocument()`)

Now, you might want to navigate to a CFI location *after* the EPUB is loaded. In which case you can invoke:
`readium.reader.openSpineItemElementCfi(spine_item_idref, spine_item_contentCFI, readium.reader);`

**Comment by hz0324** [comment]
It works.
Thank you very much.
