### ISSUE TITLE
Patch IE10/11 self-closed tags when loading iframe

### ISSUE THREAD

**Issue by kimtuck** [readium/readium-js#145]
When loading the iframe, IE10/11 is handled specially.  If the document being loaded has self-closing tags, then when the content is converted to text and then loaded into the iframe, the DOM is incorrectly rendered by the browser.

The fix is to replace self-closed tags with properly closed tags.

**Comment by danielweck** [comment]
duplicate?
https://github.com/readium/readium-js/pull/136
