### ISSUE TITLE
Is that possible to get the CFI of the first character visible on the screen?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#146]
We want to build an easy-to-understand bookmark system, for example, when user bookmark one page, when he/she comes back, the returned page should start at the same Character/Position. I have tried the existed bookmarkCurrentPage() api, I don't really understand how it defines the Current Page. I found it give me the different start point when the screen size changes. 

If I can get the CFI as marked in the screenshot, problem can be solved.
![qq 20161114170016](https://cloud.githubusercontent.com/assets/5040078/20258729/f767f9f6-aa8b-11e6-852d-060818809957.png)

Is that possible?
Thanks

**Comment by danielweck** [comment]
`var bookmark = JSON.parse(readium.reader.bookmarkCurrentPage());` obtains the CFI reference of the upper-left "corner" of the page spread. If this doesn't work, then it's a bug. Could you please elaborate?

The "share reader bookmark..." button in the cloud reader (on the right side of the top toolbar) also utilizes `readium.reader.bookmarkCurrentPage()` to obtain a reference of the content "area" that the user is currently looking at. This feature constructs a `goto` URL parameter that can then be used to restore the saved reading location, e.g.:
https://readium.firebaseapp.com/?epub=epub_content%2Faccessible_epub_3&goto=%7B%22idref%22%3A%22id-id2442754%22%2C%22elementCfi%22%3A%22%2F4%2F2%5BI_book_d1e1%5D%2F2%2C%2F1%3A0%2C%2F1%3A1%22%7D

(note how the upper-left character is temporarily highlighted in yellow, this is a DEBUG helper)
