### ISSUE TITLE
readium.reader.setBookStyle(styles) dosen't update the current content displayed accordingly.

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#147]
I am using the setBookStyle() API to change the fontSize of the book, as following.

![qq 20161116143433](https://cloud.githubusercontent.com/assets/5040078/20337162/402feb1a-ac0a-11e6-9a62-ddb25bb1ed9e.png)

The problem is, after running these code, no change happened on the content that are displayed on the screen, but if you change to another chapter using toc, the change become effective. 

How to solve this problem?
Please help.
Thanks

PS: the default fontSize is 16.

**Comment by danielweck** [comment]
Use `this.readium.reader.updateSettings(val);`, with `val` = 
```json
{
    fontSize: data,

    syntheticSpread: "auto",  // other values allowed, this is just an example
    columnGap: 60,  // other values allowed, this is just an example
    columnMaxWidth: 700,  // other values allowed, this is just an example
    scroll: "auto"  // other values allowed, this is just an example
}
```

**Comment by danielweck** [comment]
See:

https://github.com/readium/readium-shared-js/blob/develop/js/models/viewer_settings.js#L32
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L560
https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L147
vs.
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L834
https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L390

**Comment by hz0324** [comment]
Thank you very much
