### ISSUE TITLE
What are the differences among setBookStyle(), setStyles() and updateSettings()? 

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#148]
I am so confused of these three, the API docs define three new words, but what exactly are they referencing?

![qq 20161117103101](https://cloud.githubusercontent.com/assets/5040078/20374118/51184c18-acb1-11e6-95fc-68a3410a5375.png)
![qq 20161117103127](https://cloud.githubusercontent.com/assets/5040078/20374124/573a8958-acb1-11e6-84e8-3b6e2ee4d8f3.png)

1, **content document** in setBookStyle()
2, **reader container** in setStyles()
3, **reader view** in updateSettings()

What are they? How to decide which to use when comes to changing the book css settings, for example, line-height, word-space or even add new css to certain element node?

Thanks

**Comment by danielweck** [comment]
`setBookStyles()`
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L834
=> injects custom CSS style definitions into loaded spine items / EPUB documents (note that styles are attached to the root `html` element, so authored styling may or may not take precedence, depending on the usual CSS cascading and priority rules).

See `Helpers.setStyles()`:
https://github.com/readium/readium-shared-js/blob/develop/js/helpers.js#L598

See `applyBookStyles()` in the reflowable view:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L390

Note that `applyBookStyles()` in the fixed layout view is disabled (authored styling is never overriden):
https://github.com/readium/readium-shared-js/blob/develop/js/views/one_page_view.js#L422
(PS: `one_page_view` is also used for the per-document and continuous scroll mode, not just for fixed layout)

**Comment by danielweck** [comment]
`setStyles()`
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L812
=>
`applyStyles()`:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L900
reflow:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L376
fixed-layout:
https://github.com/readium/readium-shared-js/blob/develop/js/views/fixed_view.js#L223
scroll:
https://github.com/readium/readium-shared-js/blob/develop/js/views/scroll_view.js#L697

=> applies custom CSS style definitions to the *container* HTML markup of each `iframe` that host individual EPUB documents / spine items. For example, coloured borders, fake / skeuomorphic paper book look, extra side margins, etc.

See the default CSS stylesheet here:
https://github.com/readium/readium-shared-js/blob/develop/static/sdk.css
Also see the HTML templates (markup structure) for each view, `Helpers.loadTemplate.cache`:
https://github.com/readium/readium-shared-js/blob/develop/js/helpers.js#L582

**Comment by danielweck** [comment]
`updateSettings()`
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L560
=> See `ViewerSettings`:
https://github.com/readium/readium-shared-js/blob/develop/js/models/viewer_settings.js#L32

**Comment by danielweck** [comment]
Note that `fontSize` in `ViewerSettings` also changes the "line height", see `UpdateHtmlFontSize()`:
https://github.com/readium/readium-shared-js/blob/develop/js/helpers.js#L242

Note that there is a feature branch / Pull Request with support for "font family":
https://github.com/readium/readium-js-viewer/pull/540

For word-spacing, better use `setBookStyles()` (i.e. basic CSS styling rules injected to the root `html` element of each spine item content document), but eventually it would be nice to implement a more sophisticated algorithm similar to `Helpers.UpdateHtmlFontSize()` so that user-specified styles are properly "forced" into the DOM tree.

**Comment by hz0324** [comment]
It's far complicated than I thought, I guess I have to spend more time on this.
Thank you very much
