### ISSUE TITLE
Help, openPageRequest not working properly when reopen a book.

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#152]
We have mimic the demo code of cloud-reader to build our own app.

We also store the CFI information in the local storage, use "ReadiumSDK.Events.PAGINATION_CHANGED" event to detect page change and save the pagination info using bookMarkCurrentPage() method, when reopen a book, the app get CFI information from the localstorage and asign it to openPageRequest viable, just as the demo code shows.

But, the openPageRequest in openPackageDocument() is not always working, sometimes it works, but sometimes it only jump to the start of the document stated by idref. It's really hard for us to debug, because the behavior is inconsistent.  

Sometimes, even hard coded the openPagaRequest in the code dosen't work as will.

Any suggestion for debug or fix?
Thank you very much

**Comment by danielweck** [comment]
Hello
are you able to reproduce this behaviour with Readium's own cloud reader app?
master or develop branch?
Do you include proprietary code patches in your app, that could influence the pagination / layout process?

**Comment by hz0324** [comment]
@danielweck 
Hi,
As far as now, I can not reproduce this on Readium's cloud reader. It works pretty well.
We do have written some codes to rearrange the layout after the book is rendered, in order to fit our design.  As below:
![qq 20161207213844](https://cloud.githubusercontent.com/assets/5040078/20969791/94f66996-bcc5-11e6-87a2-1224e06bbf7d.png)


Can this have effect on openPackageDocument() process?

PS: we use bookMarkCurrentPage() and openSpineItemElementCfi() to implement a bookmark systerm, which works pretty well. We are also suspecting the problem is related to rearrangement after the render, but we are not sure.

**Comment by hz0324** [comment]
@danielweck 

I guess I have fo

**Comment by hz0324** [comment]
@danielweck Hi, I think we have got the reason, you are right, the code we added after the openPackageDocument() method to reset layout/styles is the problem. When it deleted, everything works fine.

But we got another problem, where should we write the code to reset bookstyle and reader settings? It seems like, as long as there is something change, for example, font-size, the book will fly to previous pages.

**Comment by hz0324** [comment]
I have tried on cloud reader in chrome. It has the same problem after changing font-size. It cannot jump to the right place when reopen a book.

**Comment by danielweck** [comment]
In `readium-js-viewer`, the "default" settings are taken into consideration early in the `initReadium()` function:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L1004
See the call to `Settings.getMultiple()` within which `Settings.put('reader', ...)` is invoked.
The actual default settings are located here:
https://github.com/readium/readium-js-viewer/blob/develop/src/js/ReaderSettingsDialog.js#L4
...and this takes precedence over the `readium-shared-js` default values:
https://github.com/readium/readium-shared-js/blob/develop/js/models/viewer_settings.js#L32

*After* that early initialization step (just further down in the source code), the `openPageRequest` is constructed (using the "saved reading location", or the "shared bookmark" from the `goto` URL query parameter). Then the `readium-js` "main" object is instantiated:
`readium = new Readium(readiumOptions, readerOptions);`
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L1104
...and finally `readium.openPackageDocument()` is invoked to actually start loading + rendering the EPUB at the given location.
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L154

PS: feel free to suggest architectural improvements. This is by no means a locked-down proposition. The current design has undergone incremental changes over time, but in some places the codebase could benefit from deeper refactoring, especially to make it easier for ReadiumJS integrators to customize default behaviour without having to hack into the core source code.

**Comment by hz0324** [comment]
@danielweck Thank you very much for your help.
Today we managed to solve this problem by doing it like this:

1. use openPackageDocument() while giving null to openPageRequest;
2. recover the book settings, such as color and font-size from localstorage, which stores all book settings
3. after the setting process is done,  calling openSpineItemElementCfi() to jump to the right place. It works just fine.

**But**, we do have some problem: when to call the openSpineItemElementCfi()?
If we call this method just after the book is loaded (not a accurate time point,I just mean when we can see the cover), it woundn't work. We guess it has something to do with the ongoing background processing which can not be seeing from the view of end user, it has to wait for a special point, such as something is loaded, to let openSpineItemElementCfi() work properly.

Then we tried two method:
1. First, we use setTimeout to delay the calling of openSpineItemElementCfi(), it works, but really undesirable.
2. We add this method to onDoucmentReady event(not the exact name, I forgot it). It really works, but having a noticiable lag.

We are guessing there must be another event callback we can use to accelerate this process. We just don't know which one to use? Can you give us some help on this? 

Thank you very much again for your excellent work.
