### ISSUE TITLE
How to let the readium re-calculate the page counts needed for a spine document?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#161]
In order to solve the image split problem in auto scroll mode, we change the css settings of img elements in `ReadiumSDK.Events.CONTENT_DOCUMENT_LOADED` event. After doing so, we found a new problem. Sometimes, the page count should be re-calculate in order to fit the content more accurately. But how to invoke a re-calculation and relayout?

Or , is there a way to change the css or html file before the spine document is loaded into the iframe? 

Thanks.

**Comment by danielweck** [comment]
This "resize sensor" feature is already available in the develop branch.
A pagination pass is automatically triggered when the overall dimensions of loaded EPUB content documents (HTML files) changes.
Give it a try please, and let us know how it goes.

**Comment by danielweck** [comment]
I am closing this issue for now, but please feel free to reopen if the currently-implemented feature does not suit your needs.

**Comment by hz0324** [comment]
Thank you, I will do it when I have time, now we are struggling to finish the project on time.
