### ISSUE TITLE
Deployment build

### ISSUE THREAD

**Issue by sarankup** [readium/readium-js#162]
Hi,

Are there any build which I can host in the static hosting without node.js dependancy. For example, epub.js doesn't require any server-side programming language. Is it available in Readium?

Please advise.

**Comment by danielweck** [comment]
Yes, ReadiumJS "cloud reader" *is* a pure client-side app without any server-side code dependencies.
See `readium-js-viewer` README:
https://github.com/readium/readium-js-viewer/blob/develop/README.md#cloud-reader-deployment

Creating your own build requires NodeJS, but you can download a ready-made app from the GitHub `releases` section:
https://github.com/readium/readium-js-viewer/releases
(e.g. `Readium_cloud-reader.zip`)
