### ISSUE TITLE
Goto Function

### ISSUE THREAD

**Issue by sarankup** [readium/readium-js#163]
Hi,

I embed the Readium in my web application. I have my own Goto Page UI to some #id of the document. Please advise where to refer the API Docs. As user click my UI I would like the Readium to navigate the param page.

Please advise.

**Comment by danielweck** [comment]
The ReadiumJS "cloud / web reader" implements a similar "goto" feature, which is basically a URL query string that serializes the JSON syntax of the `openPageRequest` parameter of the `openPackageDocument()` function:

https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L1111
https://github.com/readium/readium-js-viewer/blob/develop/src/js/EpubReader.js#L156
https://github.com/readium/readium-js/blob/develop/js/Readium.js#L96
