### ISSUE TITLE
package.json has "zipjs" instead of correct "zip-js", causing yarn to install module with wrong directory name and breaking build

### ISSUE THREAD

**Issue by da70** [readium/readium-js#165]
Incorrect module name in package.json: "zipjs" should be "zip-js"

#### Related issue(s) and/or pull request(s)
[readium-shared-js #356](https://github.com/readium/readium-shared-js/issues/356)
[readium-shared-js #362](https://github.com/readium/readium-shared-js/issues/362)

PR: #167

#### Expected Behaviour

When installing dependencies using [yarn](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiemJKy0ODQAhVDW5AKHfcbCV0QFggcMAA&url=https%3A%2F%2Fyarnpkg.com%2F&usg=AFQjCNFroCU9gpWAHS2N0ZdHNYurDzRu_w&sig2=1Q8ecPVlHZ557l1rWf3iDA), should create directory `node_modules/zip-js/` instead of `node_modules/zipjs/`.

`npm run dist` should then run successfully to completion.

#### Observed behaviour

Running `yarn` installs the module in `node_modules/CSSOM/` instead of `node_modules/cssom/`, because the dependency is incorrectly named in the `package.json` file.

`npm run dist` then fails with error:

```shell

...

Error: Error: ENOENT: no such file or directory, open '/Applications/MAMP/htdocs/readium-js-viewer/readium-js/node_modules/zip-js/WebContent/zip.js'

```

#### Steps to reproduce

Pre-requisite: install [Yarn](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiirffi0-DQAhXJlJAKHYAWDZcQFggcMAA&url=https%3A%2F%2Fyarnpkg.com%2F&usg=AFQjCNFroCU9gpWAHS2N0ZdHNYurDzRu_w&sig2=iyL1FL-MBKfO6z3TiIM0-g)

1. `git clone git@github.com:readium/readium-shared-js.git`
2. `cd readium-shared-js`
3. `yarn`
4. Confirm that `zip-js` module directory is named `node_modules/zipjs/`, after the incorrect name in `package.json`.

To verify that this breaks `npm run dist` of the viewer itself, go to existing `readium-js-viewer` and do the steps inside the `readium-js` sub-module and then run the dist build.

### Product

* Readium cloud reader app
  * `master` branch as of [71df2031ba26c81ac50d2214b2f45072b9f92b39](https://github.com/readium/readium-shared-js/commit/71df2031ba26c81ac50d2214b2f45072b9f92b39).

#### Additional information

Currently, the `package.json` file contains this:

```json
  "devDependencies": {
    ...
    "zipjs": "danielweck/zip.js",
    ...
  },
```

The dependency name "zipjs" should be "zip-js" to match the `name` field in that module's `package.json`.  See [package.json - line 2](https://github.com/danielweck/zip.js/blob/master/package.json).

See "Additional information" section of [readium-shared-js #356](https://github.com/readium/readium-shared-js/issues/356) for more discussion.

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-js/pull/167

**Comment by da70** [comment]
@danielweck, thanks much for merging.  Would you be able to cherry-pick to master as you did previously with the similar fix for [readium-shared-js #356](https://github.com/readium/readium-shared-js/issues/356)?

**Comment by danielweck** [comment]
@da70 My personal opinion (as a regular Readium contributor / maintainer) is that "hotfixes" to the `master` branch should only occasionally be used, in cases where the standard NPM-driven build is broken. Right now Yarn is not really "officially" supported in ReadiumJS (i.e. tested in the field by several regular contributors). Travis continuous integration uses NPM too.

That being said, release 0.25 is coming up soon, so any recent change in the `develop` branch will be merged into `master`, and release-tagged.

Side note: I'm really glad you started this conversation, thank you not only for your pull requests, but also for the detailed analysis / commentary you provided in the issue tracker.

**Comment by da70** [comment]
@danielweck Sure, I understand completely.
I will make a note to keep an eye out for release 0.25.  In the meantime I put in a workaround to get our yarn build working, so our workflow is not obstructed.  Thanks for your speedy responses, and I'm glad that my issues comments could be helpful in some way.
