### ISSUE TITLE
Is there a hidden method that can get cfi for certain element?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#170]
Just like using `getElementByCfi(spineItem, cfi, classBlacklistopt, elementBlacklistopt, idBlacklistopt)` can give me the element for a given cfi.
Is there a hidden method in readium that can give me a cfi for given element? For example,` getCfiForElement(ele)`

Thanks

PS: I have tried to look at how you guys implement `getCurrentSelectionCfi()`, but failed to find the code snippet.

**Comment by danielweck** [comment]
https://github.com/readium/readium-shared-js/blob/develop/js/views/reader_view.js#L1730
```javascript
    this.getCfiForElement = function(element) {
        if (_currentView) {
            return _currentView.getCfiForElement(element);
        }
        return undefined;
    };
```
