### ISSUE TITLE
Build error: eventemitter3/_rjs/index.js not found

### ISSUE THREAD

**Issue by antelopeb** [readium/readium-js#172]
This project is included as a submodule in another Git based project. I installed all submodule dependencies, npm installed all three repos (readium-js, readium-shared-js, readium-cfi-js) and then ran "npm run build" inside the readium-js directory.

It errors out thus:
```
Plugins bundle config:
../../build-config/RequireJS_config_plugins_multiple-bundles.js
[ '../build-config/RequireJS_config_common.js',
  '../build-config/RequireJS_config_multiple-bundles.js',
  '../../build-config/RequireJS_config_plugins.js',
  '../../build-config/RequireJS_config_plugins_multiple-bundles.js',
  '../../build-config/RequireJS_config_common.js',
  '../../build-config/RequireJS_config_multiple-bundles.js',
  '../../../build-config/RequireJS_config_multiple-bundles_external-libs.js',
  '../../../build-config/RequireJS_config_common.js',
  '../../../build-config/RequireJS_config_multiple-bundles.js' ]
Error: Error: ENOENT: no such file or directory, open '/Users/gregda/Git/erpi-reader/readium-js/readium-shared-js/node_modules/eventemitter3/_rjs/index.js'
    at Error (native)
```

When I remove the _rjs in the path, it builds, but then errors out in browser saying that EventEmitter is undefined.

**Comment by antelopeb** [comment]
Nevermind. I found that if I go into the submodule "readium-shared-js" and manually run "npm run prepare" before building readium-js, the errors go away.

**Comment by danielweck** [comment]
just FYI:
the 'npm run prepare' command can be invoked at any level of the nested readium-* repositories, and the command will automatically "recurse" inside each submodule folder.
Invoking 'npm install' or 'npm update' manually is not sufficient. Use 'npm run prepare' instead.

**Comment by antelopeb** [comment]
That was my mistake... thanks!

**Comment by danielweck** [comment]
No problems...I blame the documentation writers ;)

**Comment by manojchandrashekar** [comment]
I still had the issue after running prepare in the submodule. This helped me solve the issue: https://github.com/readium/readium-js-viewer/issues/509
