### ISSUE TITLE
Is there a way to get access to the content in a spine without rendering it to a iframe?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#174]
I am trying to develop a full-content searching system. So I need to get access to the content of certain spine itmes. A STUPID way to do it is rendering each spine items to the iframe iterately. But when it come to  some giant book which may has hundreds of spines, this approach can be pretty slow.

So I am wondering whether there is a way to access a spine's content (html file content) without rendering it to the actual DOM. Hope you guys can help.

Thanks.

**Comment by danielweck** [comment]
In ReadiumJS, that's what the `PublicationFetcher ` is for.
For example: `fetchContentDocument()`, or alternatively `getXmlFileDom()` and `getFileContentsFromPackage()`:
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/publication_fetcher.js#L167
