### ISSUE TITLE
generateTocListDOM() returns useless DOM tree, please help.

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#175]
About few months ago, someone told us how to get TOC when open a book. As following:
![1](https://cloud.githubusercontent.com/assets/5040078/24180158/3f968a96-0eee-11e7-8b73-35da774ede38.png)

Now our web app has launched, but we found that for some books, readium returns a whole document DOM containing no useful TOC data as below:
![3](https://cloud.githubusercontent.com/assets/5040078/24180162/43decca8-0eee-11e7-8077-c5a16386f01f.png)

Normally, a book should return a DOM structure like this:
![2](https://cloud.githubusercontent.com/assets/5040078/24180166/4893fe44-0eee-11e7-8d14-c7d1495d8a18.png)

We have tried the books that returns "Bad" DOM structure in Readium Chrome App, the TOC function works pretty well. 

We don't know how to solve the problem. Maybe we are using the wrong way to get TOC data？

Please help, Thanks.

**Comment by danielweck** [comment]
hello, the first thing that comes to mind is the fact that your webapp / cloud reader example (looking at your debugger screenshots) seems to involve opening a zipped / packed publication container, rather than an exploded / unzipped / unpacked EPUB file.
So, could you please try extracting the EPUB resources on the server, then point your web reader URL to the root folder?
Let me know is how it goes.
daniel

**Comment by danielweck** [comment]
secondly, have you tried loading the same EPUB with the standard build of the ReadiumJS cloud reader?
eg.
https://readium.firebaseapp.com/?epub=YOUR_EPUB_URL

**Comment by hz0324** [comment]
Hi, Daniel. Thanks for your reply.

Yes, we did load the zipped epub book directly from the browser, we load the book as a File object, most book works just fine. Our app dosen't use a server to do any work related to book rendering. So we can not rely on any server-side code. 

Yesterday, I have looked into the readium-reader-lite's code and try to use the code found there to rewrite our Toc component. Now I can successfully loaded the toc dom to a special DIV, all toc items showed up as expected.

The code we are using now shows below:
![qq 20170323111305](https://cloud.githubusercontent.com/assets/5040078/24230383/d2dcb05c-0fb9-11e7-8bef-d1edf5f62242.png)

Now the Toc items shows up as expected, the only different is that: we didn't put append the dom given by `generateTocListDOM()`. However, we got another problem. The href attribute of each <a> element is not ok for `openConetentUrl()`.  As you can see in the following screenshot. The correct href should have one more folder structure before it. I have tested the "Text/xxxx.xhtml", it did works. However, this book toc works pretty well in readium chrome app as well. 
![qq 20170323111640](https://cloud.githubusercontent.com/assets/5040078/24230508/790a4052-0fba-11e7-94af-b6c8cfb3c0e1.png)

The sturcture of the epub book when unzipped
![qq 20170323112030](https://cloud.githubusercontent.com/assets/5040078/24230575/ca08df7c-0fba-11e7-84bc-1189e90f910e.png)

So we are stucked again now. We don't know how to solve this problem. 
I have tried to look into the readium code in `EpubReader.js`, but nothing helpful was found.

Can you please help us?
Thanks.

**Comment by hz0324** [comment]
BTW, we want to keep the url clean, for example, no matter what book user opens, the url seen on the browser will always be http://ourapp.com. So we don't want to rely this to redirect user to specific part.

**Comment by hz0324** [comment]
@danielweck Please help us, sir.

**Comment by hz0324** [comment]
I am colsing it because we totally copied the code in readium example and it works. We don't know the reason yet, but this is not a issue anymore.
Thanks.
