### ISSUE TITLE
Question：how to render a epub file with DRM? 

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js#177]
A company want to hire us to build a web reading system.
They'd like to host their books with DRM in their server and let us build a front-end reader to access these books. What are the solutions we have by using ReadiumJS?

Thanks.
I can not find any information about this topics, please help.

**Comment by llemeurfr** [comment]
I can say that Readium LCP libraries have been developed for mobile and desktop implementations, but we don't intend to implement DRM on a pure web client implementation, as we don't see how such implementation can be secure.

**Comment by hz0324** [comment]
@llemeurfr  Thank you for your reply.

What about server-side processing DRM and front-end only rendering books? Is this approach possible?

**Comment by llemeurfr** [comment]
Sure it is possible. And then authentication + HTTPS protect content during its move from the server to the client, in a "streaming" mode. The Readium-2 architecture, with its Golang "streamer" module, is made just for that.

**Comment by hz0324** [comment]
@llemeurfr 

Great, could you please tell me where I can find information about how to do it. I didn't see any document for this.

Thanks

**Comment by llemeurfr** [comment]
If you want to look at this path, you'll find info in -> https://github.com/readium/readium-2 (architecture, doc) and https://github.com/readium/r2-streamer-go (golang streamer). You'll have to browse the project to learn how we work. We'd like help to developer a new JS "navigator", i.e. an update of Readium JS.
