### ISSUE TITLE
readium-js does not build with npm v4

### ISSUE THREAD

**Issue by briantobo** [readium/readium-js#178]
#### Expected Behaviour
npm downloads all dependencies when running ```npm run prepare``` and is ready to build

#### Observed behaviour
npm fails to download dependencies

#### Steps to reproduce
```
git clone https://github.com/readium/readium-js.git
git submodule update --init --recursive
git checkout BRANCH_NAME && git submodule foreach --recursive "git checkout BRANCH_NAME"
npm run prepare
```

### Product
* Hybrid app (ReadiumJS)

#### Additional information
I think there are at least two issues that need fixing here.

1. With npm 4.x ```npm outdated``` exits with status != 0 when there are package that need to be updated. This makes the idiom ```npm outdated && npm install && npm update``` fail. This is noted in https://github.com/npm/npm/releases/tag/v4.0.0
2. With npm 4.x, the command ```npm prepare``` is executed after a package is installed. This causes a loop in the readium-js project where ```prepare``` executes ```install``` which executes ```prepare``` again etc. This is also noted in https://github.com/npm/npm/releases/tag/v4.0.0

This problem also affects readium-shared-js and readium-cfi-js since they are dependencies of readium-js and use the same structure for package.json.

I'm not sure how to fix this while keeping compatibility with npm v3 since the behaviors of some commands has changed between versions. Any help would be greatly appreciated !

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-js-viewer/issues/600 and https://github.com/readium/readium-js-viewer/issues/622

**Comment by danielweck** [comment]
Fixed `readium-cfi-js`: https://github.com/readium/readium-cfi-js/commit/96540abe8bac1bf58bcac56ecf6c59acea3c4b46

...now onto the other repos (will report here as it happens).

**Comment by danielweck** [comment]
Note that the `readium-cfi-js` build passes on Travis CI, with a NodeJS matrix 4, 5, 6, and v7.
https://travis-ci.org/readium/readium-cfi-js/builds/235973237

**Comment by danielweck** [comment]
Just to clarify the `prepare` issue: the README has been updated with the new `package.json` script name: `prepare:all`. The NPM build tasks can now also be invoked with Yarn, by invoking `yarn run prepare:yarn:all` on the command line instead of `npm run prepare:all`.

**Comment by danielweck** [comment]
Fixed for `readium-shared-js`: https://github.com/readium/readium-shared-js/commit/cc02b59b4780cf5726230e3909ead57bba382460

...moving onto the next repos.

**Comment by danielweck** [comment]
Fixed in `readium-js` too: https://github.com/readium/readium-js/commit/3aaf9916eb242f3d026d0c48aaa50a2bd6f208aa

....last repo coming soon.

**Comment by danielweck** [comment]
Fixed for `readium-js-viewer`: https://github.com/readium/readium-js-viewer/commit/c9d6e0d7efd16b13236e3a918849c5bb2ac034e8

TravisCI in progress: https://travis-ci.org/readium/readium-js-viewer/builds/235992670

**Comment by danielweck** [comment]
Tested, checked, and verified (NPM, YARN, Node v6 and v7). Let's close this issue now.

**Comment by briantobo** [comment]
Thanks @danielweck, this seems to be working great in the develop branch :)

**Comment by r-a-y** [comment]
Thanks @danielweck , I can also confirm that this is working on the `develop` branch.
