### ISSUE TITLE
Font decryption fails

### ISSUE THREAD

**Issue by daniel-j** [readium/readium-js#183]
I have deployed the Readium cloud reader on my web server, and noticed that encrypted fonts don't render. After playing around with the epub contents and stepping through the Readium-JS code, I found out that if you remove the prefix `enc:` from all elements in the `encryption.xml` file, it works.
The issue is in the encryption_handler.js file [where jQuery is used](https://github.com/readium/readium-js/blob/35ba010692ff6937fe674f3ecb2d6cbfa6addeed/js/epub-fetch/encryption_handler.js#L142-L161). As you can see, it does not include looking for the nodes with the `enc:` (namespace?) prefix.
You can see an example encryption.xml file from the spec [here](http://www.idpf.org/epub/301/spec/epub-ocf.html#sec-container-metainf-encryption.xml), and it includes the `enc:` prefixes. My EPUB was created with Sigil 0.9.7 and uses Adobe's method. IDPF's method gives the same result.

#### Expected Behaviour
Decode the fonts as expected.

#### Observed behaviour
Doesn't decode the fonts and shows the fallback font.

#### Steps to reproduce
1. Create an ebook with Sigil
2. Add a font (otf or ttf) and make a css font-face and use it in the ebook
3. Apply Adobe or IDPF's protection
4. Save and open with Readium

#### Test file(s)
EPUB with `enc:` prefixes: https://books.djazz.se/epub_content/project_sunflower/notworking.epub
EPUB with the prefixes removed: https://books.djazz.se/epub_content/project_sunflower/working.epub
Online version with `enc:` prefixes: https://books.djazz.se/?epub=epub_content%2Fproject_sunflower
The font is Adobe Garamond Pro (subsetted). Ebook shared with permission.

### Product
* Readium cloud reader app
  * https://books.djazz.se/ Latest stable release
  * Chromium 60 
  * Manjaro Linux

**Comment by rkwright** [comment]
Hm.  This is very curious as there are a number of deployed instances of the CloudReader where font-obfuscation works fine.  I wonder if this how anything to do with where the files are deployed relative to the code or, alternatively some quirk relative to jquery.

BTW, LOL:  I had no idea there was a tool out there that still emitted the old Adobe font-obfuscation.  I thought ID4 was the last one.

**Comment by danielweck** [comment]
Related: 
https://github.com/readium/readium-cfi-js/pull/66

**Comment by danielweck** [comment]
Alternative to jQuery: `document.getElementsByTagNameNS('*', 'element_name')` (then wrap the matched element(s) in a jQuery object `$()`

**Comment by danielweck** [comment]
Also see: https://github.com/readium/readium-cfi-js/pull/33

**Comment by daniel-j** [comment]
7 months later. Would like to see a fix to this.

**Comment by danielweck** [comment]
I took this opportunity to load the provided sample EPUB ( https://books.djazz.se/epub_content/project_sunflower/notworking.epub ) in a Readium2 "streamer" test service:
http://readium2.herokuapp.com/pub/aHR0cHM6Ly9ib29rcy5kamF6ei5zZS9lcHViX2NvbnRlbnQvcHJvamVjdF9zdW5mbG93ZXIvbm90d29ya2luZy5lcHVi/manifest.json/show/all
...the obfuscated font face is correctly handled.

**Comment by danielweck** [comment]
I believe the bug was recently fixed.
Can you please confirm:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcors-anywhere.herokuapp.com%2Fhttps%3A%2F%2Fbooks.djazz.se%2Fepub_content%2Fproject_sunflower%2Fnotworking.epub&goto=epubcfi(/6/10!/4/2/1:0)

**Comment by daniel-j** [comment]
Yes, it works now! I should have tested the latest version before my last statement. Thanks!

**Comment by mohan9000** [comment]
@daniel-j what is the fix for this

**Comment by daniel-j** [comment]
@mohan9000 I don't know what the fix was, only that a newer version at the time solved it. Have you tried my notworking.epub file?
https://books.djazz.se/epub_content/project_sunflower/notworking.epub

**Comment by danielweck** [comment]
The `encryption.xml` DOM is parsed here, using jQuery:

https://github.com/readium/readium-js/blob/9facb57dc4dc6df75eb24c0be982d0d1fd675988/js/epub-fetch/encryption_handler.js#L116

**Comment by danielweck** [comment]
The DOM parser is created on the calling side:
https://github.com/readium/readium-js/blob/9facb57dc4dc6df75eb24c0be982d0d1fd675988/js/epub-fetch/publication_fetcher.js#L416-L418

**Comment by danielweck** [comment]
As you can see, it's just a call to `parseXml()`:
https://github.com/readium/readium-js/blob/9facb57dc4dc6df75eb24c0be982d0d1fd675988/js/epub-fetch/publication_fetcher.js#L201-L203

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-js-viewer/issues/753

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-js/commit/b2c65bf3dd3b47ec716d328479a3c8af51fde0d2

**Comment by danielweck** [comment]
A new build of the web reader has been deployed. You can test your EPUB by drag-n-drop onto the browser window:
https://readium.web.app
Alternative link:
https://readium.surge.sh
You can download the latest web reader build (`Readium_cloud-reader.zip`) from:
https://github.com/readium/readium-js-viewer/releases/tag/0.32.0-alpha
