### ISSUE TITLE
External compressed ZIP ePubs not functioning on iPad (Safari, Chrome iOS)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js#51]
Originally posted by @danielcrenna
at
https://github.com/readium/readium-js-viewer/issues/65
# 

We have set up an example of loading externally-(Azure) and internally-(our server) sourced compressed EPUB files, which works as expected on desktop browsers, and even when the compressed content is served locally via Http Byte Serving on Safari for iPad.

However, remote compressed EPUBs do not function on Safari iOS or Chrome iOS, and internal compressed EPUBs do not function on Chrome iOS (they work on Safari iOS).

We know that CORS is set up properly because this setup works on every desktop browser we've tried. As always, uncompressed content works fine. Is there something specific about the EPubUnzipper or PackageParser implementations that cause this on iOS?

I am happy to share our reference implementation privately if you're interested.

**Comment by johanpoirier** [comment]
I was testing some Android devices running android 4.2.2 and I got the same issue. Remote zipped epubs are not opened.

The stock android browser refused to consider the following HTTP headers (Refused to get unsafe header):
 - Content-Length
 - Accept-Ranges

It works fine with Chrome. Do I open another issue ?

*PS: I still have a pending PR #73 which resolves this issue for iPad running iOS 6*

**Comment by danielweck** [comment]
Thank for the heads-up @johanpoirier 

@alper have you tried the latest `cloudReader` and `cloudReaderLite` builds? ('grunt' command)
Basically, `index.html` and `simpleviewer.html` can still be used to open zipped EPUBs, but now the optimized (i.e. minified and aggregated source code) `build/cloud-reader/index.html` and `build/cloud-reader-lite/index.html` work with packed EPUBs as well.

For example, using Node-Express (which starts when invoking the no-parameters `grunt` command):

`http://127.0.0.1:8080/index.html?epub=epub_content/internal_link.epub`

`http://127.0.0.1:8080/simpleviewer.html?epub=epub_content/internal_link.epub`

`http://127.0.0.1:8080/build/cloud-reader/index.html?epub=../../epub_content/internal_link.epub`

`http://127.0.0.1:8080/build/cloud-reader-lite/index.html?epub=../../epub_content/internal_link.epub`

Does that work for you?

**Comment by johanpoirier** [comment]
I performed my tests with my own cloud reader based on the latest readium-js (develop branch).

I just tested the cloudReader since you asked and the result is the same :
- Safari on iPad mini (iOS 6.1) : the spinner spins forever, no error displayed in console (I think `window.URL.createObjectURL` can be blamed) 
- Android browser on Nexus 10 (Android 4.2.2) : `Uncaught TypeError: illegal constructor` (when trying to create a new Blob: can be fixed using WebKitBlobBuilder I think)

**Comment by danielweck** [comment]
Thanks for the updated tests!

**Comment by danielweck** [comment]
I believe this should be solved by PR https://github.com/readium/readium-js/pull/193 and by setting up correct HTTP CORS headers on the content server. Closing this old issue.
