### ISSUE TITLE
Some browsers do not support URL Blob constructors (Android, iOS, etc.?)

### ISSUE THREAD

**Issue by johanpoirier** [readium/readium-js#72]
In https://github.com/readium/readium-js/blob/develop/epub-modules/epub-fetch/src/models/iframe_zip_loader.js, window.URL.createObjectURL is used to build the documentDataUri which is then set to the src attribute of the iFrame.

Safari 6 consider this URI as not valid and therefore not open it.
The URI looks like this : blob:http://myipadress/237c92f5-92c6-46c5-a0d8-2c63233e5f22

Any idea how to prevent this ?

**Comment by danielweck** [comment]
Related issue?
https://github.com/readium/readium-js-viewer/issues/326

**Comment by landvibe** [comment]
When I set isIE=true, it seems all platform and browsers works well.
I wonder why we need to use the if-statement.

**Comment by danielweck** [comment]
@landvibe `document.open()/write()` does not support the XHTML content-type (only `text/html`) ; unlike `window.URL.createObjectURL(new Blob([data], {'type': "application/xml+html"})` ; which results in broken namespaced CSS selectors such as those that query `@epub:type` attributes (+ some other XML-dependent EPUB3 features).

https://github.com/readium/readium-js/blob/develop/epub-modules/epub-fetch/src/models/iframe_zip_loader.js#L67

**Comment by danielweck** [comment]
Quoting @landvibe from another issue (#326):

https://github.com/readium/readium-js-viewer/issues/326#issuecomment-98621602

Adding two lines of code fixes this issue.

zip-ext.js -> HttpRangeReader -> init (add below line after request.open)
request.setRequestHeader("If-None-Match","webkit-no-cache");

zip-ext.js -> HttpRangeReader -> readArrayBuffer (add below line after request.open)
request.setRequestHeader("If-None-Match","webkit-no-cache");

**Comment by danielweck** [comment]
@johanpoirier what do you think about @landvibe 's suggested solution above?
HTTP header 'If-None-Match' = `webkit-no-cache`

**Comment by landvibe** [comment]
@danielweck do you have any example(epub file) that I can see the 'broken namespaced CSS selectors'?

**Comment by danielweck** [comment]
@landvibe have a try with this EPUB: https://www.dropbox.com/s/z3nwobgfv7h51s2/xhtml5_test.epub?dl=0
(let us know what your findings are, please)

**Comment by landvibe** [comment]
@danielweck

Below browsers works well
* android(4.4.2) native and chrome
* OSX(10.10.1) safari and chrome
* iOS(8.3) safari

Below browser has wrong color. The second column(EPUB TYPE) renders white (not yellow).
(I modified source code that set isIE=true on iOS chrome, otherwise the indicator spins forever)
* iOS(8.3) chrome

**Comment by danielweck** [comment]
TODO: use browser detection for IE, Edge, iOS<7, and BlobBuilder. See TEA work:
https://github.com/TEA-ebook/readium-js/blob/tea/js/epub-fetch/iframe_zip_loader.js#L115

**Comment by danielweck** [comment]
TODO: 
https://github.com/danielweck/zip.js/blob/master/WebContent/zip-ext.js

Quoting @landvibe from another issue (#326):

https://github.com/readium/readium-js-viewer/issues/326#issuecomment-98621602

Adding two lines of code fixes the issue of packed EPUB loading on some platforms:

zip-ext.js -> HttpRangeReader -> init (add below line after request.open)
`request.setRequestHeader("If-None-Match","webkit-no-cache");`

zip-ext.js -> HttpRangeReader -> readArrayBuffer (add below line after request.open)
`request.setRequestHeader("If-None-Match","webkit-no-cache");`

**Comment by danielweck** [comment]
We need to update the fix from this Pull Request: https://github.com/readium/readium-js/pull/73
(to make things simpler in our tests, just force `var isIE = true;`, and check the results)

**Comment by danielweck** [comment]
New PR: https://github.com/readium/readium-js/pull/193

**Comment by danielweck** [comment]
w
