### ISSUE TITLE
Make it possible for epubs to be served from a different domain

### ISSUE THREAD

**Issue by vanisuthamathi** [readium/readium-js#74]
Verified using readium-js-viewer in different browsers with enabling Access control allow origin in the backend from where the epubs are fed to the readium-js-viewer . Below are the errors:
-In Firefox Browser
"epubReadingSystem INJECTION ERROR! Permission denied to access property 'navigator'" 

-In Chrome Browser
epubReadingSystem INJECTION ERROR! Blocked a frame with origin "http://portal.newgen.co" from accessing a cross-origin frame.
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://portal.newgen.co" from accessing a frame with origin "http://commondatastorage.googleapis.com". Protocols, domains, and ports must match. 

we had to get around this problem by running Chrome with cross-origin security turned off:  path/to/chrome --disable-web-security. This is not feasible when the readium reader is deployed in the apache server as a part of our web site.

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-js-viewer/issues/336
