### ISSUE TITLE
Font decryption fails

### ISSUE THREAD

**Issue by mpienkowski** [readium/readium-js#76]
When I open an epub with encrypted fonts readium tries to decrypt them. It fails to create encryption data (encryption_handler.js:114), because lib/2.5.3-crypto-sha1.js isn't loaded.

I don't see it in rjs_require_config.js, shouldn't it be there? Adding it there (plus in define clause in envryption_handler) or simply loading this file in </script> tag solves the problem.

Reproduced on versions 0.14 and 0.15.

**Comment by danielweck** [comment]
Fixed via RequireJS refactoring (NPM-based build workflow, no duplicate hard-coded libs):
https://github.com/readium/readium-js/blob/develop/package.cson#L103
`"crypto-js": 'latest'`
