### ISSUE TITLE
Blob URLs violates CSP in Firefox OS apps

### ISSUE THREAD

**Issue by johanpoirier** [readium/readium-js#83]
[Privileged and certified apps](https://developer.mozilla.org/fr/Firefox_OS/Security/Application_security#App_Types) in Firefox OS enforce a [CSP](https://developer.mozilla.org/en-US/Apps/CSP) by default.

Therefore, ``<link href="blob:xxxx-xxxx-xxxx-xxxx" rel="stylesheet">`` is rejected. The only workaround I found is to put the stylesheet data in a ``<style type="text/css">`` element as 'unsafe-inline' is authorized for privileged apps. I can't submit a PR yet because I don't like my implementation.

But I'm very interested in your thoughts about this.

**Comment by rkwright** [comment]
Closing as stale
