### ISSUE TITLE
Empty title in HTML file causes IE to display a blank page

### ISSUE THREAD

**Issue by johanpoirier** [readium/readium-js#86]
Hi,

I have an excerpt from an epub file that have some html files with empty titles : `<title></title>`.
If the epub is packaged, the [iframe_zip_loader](https://github.com/readium/readium-js/blob/develop/epub-modules/epub-fetch/src/models/iframe_zip_loader.js) is used to open files and parse the content.
DOMParser is then used to parse the html content : DOMParser is a XML parser and outputs `<title/>`which is not allowed in HTML (and causes IE to display a blank page).

I have a quick fix in mind : fill the `<title>`tag if it's empty. **Do you have a better solution ?**

Thanks,
Johan

**Comment by danielweck** [comment]
I think this was fixed here:
https://github.com/readium/readium-js/blob/develop/js/Readium.js#L63

...but there is a pending PR with a more generic solution:
https://github.com/readium/readium-js/pull/136/files#diff-d45cdc8100690ade3fbd3b563a26b51bL66

**Comment by johanpoirier** [comment]
👍
