### ISSUE TITLE
Windows Store WebView "safe" DOM mutations

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js#91]
Some methods are not covered by default by winstore-jscompat (see https://github.com/MSOpenTech/winstore-jscompat/ ), for example document.write() which is used by `zipIframeLoader`: https://github.com/readium/readium-js/blob/develop/epub-modules/epub-fetch/src/models/iframe_zip_loader.js#L81

Fix using wrapper:
```
if (window.MSApp && window.MSApp.execUnsafeLocalFunction) {}
```

**Comment by danielweck** [comment]
index.html (or reader.html depending on the naming convention) should include:

```
<script type="text/javascript" src="winstore-jscompat.js"></script>
```

**Comment by danielweck** [comment]
Fixed here: https://github.com/readium/readium-js/commit/5351a27f2073067d24f5a37f98ced3e9c1af0abd

...but the complete solution requires including `winstore-jscompat.js`, as per my comment above.

**Comment by mahag** [comment]
Is this a reply to this question https://github.com/readium/readium-js-viewer/issues/281 ?
I dont have this folder/subfolders/file 
epub-modules/epub-fetch/src/models/iframe_zip_loader.js
What should i do to add it ?

**Comment by danielweck** [comment]
@mahag this is unrelated to DRM / EPUB content protection / encryption.
